feat: updated scripts + modified nvim config

diff --git a/scripts/scripts/gd b/scripts/scripts/gd
--- a/scripts/scripts/gd
+++ b/scripts/scripts/gd
@@ -6,28 +6,31 @@ current_directory=$(dirs +0)
 # path to directory config script
 config_path="$HOME/dotfiles/scripts/scripts/gd-config.txt"
 
-# add new alias to config file
-# check if -a or --add argument was passed
-if [ "$1" == "-a" ] || [ "$1" == "--add" ]; then
-  echo "adding directory $current_directory"
-  echo -n "alias: "
-  read -r dir
-  echo "$dir $current_directory" >> "$config_path"
-  return 0 # using return to prevent bash script from closing terminal
-fi
-
-# remove alias from config file
-# check if -r or --remove argument was passed
-if [ "$1" == "-r" ] || [ "$1" == "--remove" ]; then
-  remove_index=$(cat -n "$config_path" | fzf --with-nth=2 | awk '{print $1}')
-  if [ -n "$remove_index" ]; then
-    sed -i "${remove_index}d" "$config_path" && echo "removed directory alias"
-  fi
-  exit 0
-fi
-
 # read directory alias mappings from config file
 directory_mappings=$(cat "$config_path")
+
+# add new directory to config file
+function add_directory() {
+  echo -n "adding directory "$current_directory" alias: "
+  read -r dir
+  echo "$dir $current_directory" >> "$config_path"
+  echo "added directory"
+  return 0
+}
+
+# remove directory from config file
+function remove_directory() {
+  remove_index=$(cat -n "$config_path" | fzf --with-nth=2 | awk '{print $1}')
+  [ -n "$remove_index" ] && sed -i "${remove_index}d" "$config_path" &&
+    echo "removed directory"
+  return 0
+}
+
+# check if -a or --add argument was passed
+[ "$1" == "-a" ] || [ "$1" == "--add" ] && add_directory && return 0
+
+# check if -r or --remove argument was passed
+[ "$1" == "-r" ] || [ "$1" == "--remove" ] && remove_directory && return 0
 
 # display the alias but select the directory
 fzf_selection=$(echo "${directory_mappings[@]}" | fzf --with-nth=1 --height 40% --border | cut -d ' ' -f2)
@@ -36,15 +39,10 @@ fzf_selection=$(echo "${directory_mappings[@]}" | fzf --with-nth=1 --height 40% 
 directory="${fzf_selection/#\~/$HOME}"
 
 # no fzf selection - exit gracefully
-if [ -z "$directory" ]; then
-  return 0
+[ -z "$directory" ] && return 0
 
 # invalid directory path - output to stderr
-elif [ ! -d "$directory" ]; then
-  echo "$directory invalid directory" >&2
+[ ! -d "$directory" ] && echo "$directory invalid directory" >&2 && return 1
 
 # cd into directory
-else
-  cd "$directory" || return 1
-fi
-
+cd "$directory" && return 0 || return 1 # cd into directory
